datasource:
  driver: mysql
  url: 127.0.0.1:3306
  params: useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&failOverReadOnly=false&serverTimezone=GMT%2B8
  username: nova1
  password: nova123456
  dbname: nova
  max-idle: 6         # 最大空闲连接
  max-pool-size: 12   # 最大连接数
  idle-timeout: 300000    # 空闲连接超时时间(ms)
  max-lifetime: 600000    # 连接最大存活时间(ms)
  connection-timeout: 3000  # 连接超时时间(ms)
